service: candidate-service
frameworkVersion: ">=1.1.1 <2.0.0"

provider:
  name: aws
  runtime: provided.al2
  stage: dev
  region: ${env:AWS_DEFAULT_REGION, 'us-west-2'}

package:
  exclude:
    - .deno_dir/gen/file
    - node_modules
    - package-lock.json

functions:
  candidateSubmission:
    handler: main.handler
    layers:
      - !GetAtt Deno.Outputs.LayerArn
    memorySize: 128
    description: Submit candidate info
    events:
      - http:
          path: candidates
          method: post

resources:
  Transform: AWS::Serverless-2016-10-31
  Resources:
    Deno:
      Type: AWS::Serverless::Application
      Properties:
        Location:
          ApplicationId: arn:aws:serverlessrepo:us-east-1:390065572566:applications/deno
          SemanticVersion: 1.32.5

plugins:
  - serverless-scriptable-plugin

custom:
  scriptHooks:
    before:package:createDeploymentArtifacts: DENO_DIR=.deno_dir deno cache main.ts && cp -R .deno_dir/gen/file/$PWD/ .deno_dir/LAMBDA_TASK_ROOT